# https://github.com/actions/stale

name: 'Close stale PRs'
on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-message: 'This PR is stale because it has been open 1 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          stale-pr-label: 'Inactive'
          #only-labels: 'Awaiting answers'
          any-of-labels:
            description: 'Only pull requests with at least one of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels.'
            default: 'Awaiting answers'
            required: true
          close-pr-message: 'This PR was closed because it has been stalled for 2 days with no activity.'
          #days-before-pr-stale: 1
          #days-before-pr-close: 1